export const CHANGE_SHOW_PRIORITY_FILTER = "CHANGE_SHOW_PRIORITY_FILTER";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const SWITCH_TAB = "SWITCH_TAB";
export const START_TIMER = "START_TIMER";
export const UPDATE_TIME = "UPDATE_TIME";
