export const PLAY_STOP_TIMER = "PLAY_STOP_TIMER";
export const SHOW_TIMER_PROGRES = "SHOW_TIMER_PROGRES ";
export const UPDATE_USER_STATE = "UPDATE_USER_STATE";
export const RESET_TIMER ="RESET_TIMER" ;
export const CHANGE_TIMER_DURATION = "CHANGE_TIMER_DURATION";